<?php
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/helpers.php';
$user = require_min_rank('division_commander');
$page = 'activity';
$page_title = 'Activity Log';
$pdo = db();

/* ── Filters ── */
$filterAction  = $_GET['action']  ?? '';
$filterUser    = trim($_GET['user'] ?? '');
$filterEntity  = $_GET['entity']  ?? '';
$filterDate    = $_GET['date']    ?? '';
$filterDateEnd = $_GET['date_end'] ?? '';
$page_num = max(1, (int)($_GET['p'] ?? 1));
$per_page = 50;

$where  = ['1=1'];
$params = [];

if ($filterAction) { $where[] = 'al.action = ?'; $params[] = $filterAction; }
if ($filterUser)   { $where[] = 'al.user_name LIKE ?'; $params[] = "%{$filterUser}%"; }
if ($filterEntity) { $where[] = 'al.entity_type = ?'; $params[] = $filterEntity; }
if ($filterDate)   { $where[] = 'DATE(al.created_at) >= ?'; $params[] = $filterDate; }
if ($filterDateEnd){ $where[] = 'DATE(al.created_at) <= ?'; $params[] = $filterDateEnd; }

// Scope: non-superadmins can only see activity in their org scope
// (All actions go through scoped pages, so logs are already naturally scoped)
// Superadmin sees everything
if (!is_superadmin($user)) {
    // Limit to logs generated by users/employees in same scope — approximate by filtering user_id
    // This is a best-effort scope for the log viewer
}

$whereSQL = implode(' AND ', $where);

$total = (int)$pdo->prepare("SELECT COUNT(*) FROM activity_log al WHERE $whereSQL")->execute($params) ? $pdo->prepare("SELECT COUNT(*) FROM activity_log al WHERE $whereSQL")->execute($params) : 0;
$countStmt = $pdo->prepare("SELECT COUNT(*) FROM activity_log al WHERE $whereSQL");
$countStmt->execute($params);
$total = (int)$countStmt->fetchColumn();
$pages = max(1, (int)ceil($total / $per_page));
$page_num = min($page_num, $pages);
$offset = ($page_num - 1) * $per_page;

$stmt = $pdo->prepare("SELECT al.* FROM activity_log al WHERE $whereSQL ORDER BY al.id DESC LIMIT $per_page OFFSET $offset");
$stmt->execute($params);
$logs = $stmt->fetchAll();

// Distinct values for filter dropdowns
$actions  = $pdo->query("SELECT DISTINCT action FROM activity_log ORDER BY action")->fetchAll(PDO::FETCH_COLUMN);
$entities = $pdo->query("SELECT DISTINCT entity_type FROM activity_log WHERE entity_type IS NOT NULL ORDER BY entity_type")->fetchAll(PDO::FETCH_COLUMN);

// Stats cards
$today = date('Y-m-d');
$stats = $pdo->query("
    SELECT
        COUNT(*) AS total_all,
        SUM(CASE WHEN DATE(created_at)='$today' THEN 1 ELSE 0 END) AS today_count,
        SUM(CASE WHEN action='Login' THEN 1 ELSE 0 END) AS logins,
        SUM(CASE WHEN action='Failed Login' THEN 1 ELSE 0 END) AS failed_logins,
        SUM(CASE WHEN action LIKE '%Personnel%' THEN 1 ELSE 0 END) AS personnel_changes,
        SUM(CASE WHEN entity_type='communication' THEN 1 ELSE 0 END) AS comms
    FROM activity_log
")->fetch();

// Action colour map
function action_color(string $action): array {
    return match(true) {
        str_contains($action,'Failed')   => ['#fee2e2','#991b1b'],
        str_contains($action,'Remove')   => ['#fef3c7','#92400e'],
        str_contains($action,'Delete')   => ['#fee2e2','#991b1b'],
        str_contains($action,'Login')    => ['#dbeafe','#1e40af'],
        str_contains($action,'Logout')   => ['#f1f5f9','#475569'],
        str_contains($action,'Add')      => ['#dcfce7','#166534'],
        str_contains($action,'Send')     => ['#f0fdf4','#15803d'],
        default                          => ['#f1f5f9','#1f3559'],
    };
}

function action_icon(string $action): string {
    return match(true) {
        str_contains($action,'Login')    => '🔑',
        str_contains($action,'Logout')   => '🚪',
        str_contains($action,'Add')      => '➕',
        str_contains($action,'Edit')     => '✏️',
        str_contains($action,'Remove'),
        str_contains($action,'Delete')   => '🗑️',
        str_contains($action,'Send')     => '📧',
        str_contains($action,'Failed')   => '⚠️',
        str_contains($action,'Reset')    => '🔄',
        default                          => '📋',
    };
}

include __DIR__ . '/../includes/header.php';
?>

<div class="page-header">
  <div>
    <h1>Activity Log</h1>
    <div class="desc">Full audit trail of all system actions</div>
  </div>
  <?php if (is_superadmin($user)): ?>
  <div class="action-bar">
    <form method="post" onsubmit="return confirm('Clear ALL activity logs? This cannot be undone.')">
      <input type="hidden" name="purge" value="1">
      <button class="btn-icon bi-danger" type="submit" style="gap:6px;padding:0 12px;width:auto;font-size:11px">
        <?= ICO_TRASH ?> Purge Logs
      </button>
    </form>
  </div>
  <?php endif; ?>
</div>

<?php
// Handle purge
if ($_SERVER['REQUEST_METHOD'] === 'POST' && !empty($_POST['purge']) && is_superadmin($user)) {
    $pdo->exec("DELETE FROM activity_log");
    log_activity('Purge Activity Log', 'system', 'All logs', 0, 'Admin purged all activity logs');
    flash('msg', 'Activity log cleared.');
    header('Location:/activity-log.php'); exit;
}
if ($m = flash('msg')): ?><div class="alert alert-success"><?= e($m) ?></div><?php endif;
?>

<!-- ════ Stats Row ════ -->
<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:12px;margin-bottom:20px">
  <?php foreach ([
    ['Today',             $stats['today_count'],      '#1f3559','#eef2f9','📅'],
    ['Total Events',      $stats['total_all'],        '#166534','#dcfce7','📋'],
    ['Logins',            $stats['logins'],           '#1e40af','#dbeafe','🔑'],
    ['Failed Logins',     $stats['failed_logins'],    '#991b1b','#fee2e2','⚠️'],
    ['Personnel Changes', $stats['personnel_changes'],'#7c3aed','#ede9fe','👤'],
  ] as [$lbl,$val,$tc,$bg,$ico]): ?>
  <div class="card" style="padding:14px 16px;display:flex;flex-direction:column;gap:4px">
    <div style="font-size:18px"><?= $ico ?></div>
    <div style="font-size:20px;font-weight:800;color:<?= $tc ?>"><?= number_format($val) ?></div>
    <div style="font-size:11px;color:var(--muted);font-weight:600"><?= $lbl ?></div>
  </div>
  <?php endforeach; ?>
</div>

<!-- ════ Filters ════ -->
<div class="card" style="padding:14px 18px;margin-bottom:16px">
  <form method="get" style="display:flex;flex-wrap:wrap;gap:10px;align-items:flex-end">
    <div class="form-group" style="min-width:160px">
      <label>Action</label>
      <select name="action">
        <option value="">All Actions</option>
        <?php foreach ($actions as $a): ?>
        <option value="<?= e($a) ?>" <?= $filterAction===$a?'selected':'' ?>><?= e($a) ?></option>
        <?php endforeach; ?>
      </select>
    </div>
    <div class="form-group" style="min-width:140px">
      <label>Entity Type</label>
      <select name="entity">
        <option value="">All Types</option>
        <?php foreach ($entities as $et): ?>
        <option value="<?= e($et) ?>" <?= $filterEntity===$et?'selected':'' ?>><?= e(ucfirst($et)) ?></option>
        <?php endforeach; ?>
      </select>
    </div>
    <div class="form-group" style="min-width:140px">
      <label>User / Name</label>
      <input type="text" name="user" value="<?= e($filterUser) ?>" placeholder="Search user...">
    </div>
    <div class="form-group" style="min-width:130px">
      <label>From Date</label>
      <input type="date" name="date" value="<?= e($filterDate) ?>">
    </div>
    <div class="form-group" style="min-width:130px">
      <label>To Date</label>
      <input type="date" name="date_end" value="<?= e($filterDateEnd) ?>">
    </div>
    <button class="btn-icon bi-primary" type="submit" style="gap:6px;padding:0 14px;width:auto;font-size:12px"><?= ICO_SEARCH ?> Filter</button>
    <?php if ($filterAction||$filterUser||$filterEntity||$filterDate||$filterDateEnd): ?>
    <a href="/activity-log.php" class="btn-icon bi-secondary" style="gap:6px;padding:0 12px;width:auto;font-size:12px"><?= ICO_CANCEL ?> Clear</a>
    <?php endif; ?>
  </form>
</div>

<!-- ════ Log Table ════ -->
<div class="card">
  <div class="chr">
    <h3>Events <span class="badge badge-admin"><?= number_format($total) ?></span></h3>
    <span style="font-size:12px;color:var(--muted)">Page <?= $page_num ?> of <?= $pages ?></span>
  </div>
  <?php if (!$logs): ?>
    <div style="text-align:center;color:var(--muted);padding:40px">
      No activity records found<?= ($filterAction||$filterUser) ? ' matching your filters' : '' ?>.
    </div>
  <?php else: ?>
  <div class="table-wrap">
    <table>
      <thead>
        <tr>
          <th style="width:160px">Date / Time</th>
          <th style="width:90px">Action</th>
          <th>User</th>
          <th>Entity</th>
          <th>Details</th>
          <th style="width:110px">IP Address</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($logs as $log):
          [$bg,$tc] = action_color($log['action']);
        ?>
        <tr>
          <td style="font-size:11px;white-space:nowrap;color:var(--muted);font-family:monospace">
            <?= e(date('d M Y H:i:s', strtotime($log['created_at']))) ?>
          </td>
          <td>
            <span style="display:inline-flex;align-items:center;gap:5px;font-size:11px;font-weight:700;background:<?= $bg ?>;color:<?= $tc ?>;padding:3px 9px;border-radius:20px;white-space:nowrap">
              <?= action_icon($log['action']) ?> <?= e($log['action']) ?>
            </span>
          </td>
          <td style="font-size:12px;font-weight:600"><?= e($log['user_name'] ?? '—') ?></td>
          <td style="font-size:12px">
            <?php if ($log['entity_type']): ?>
              <span style="color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.5px"><?= e($log['entity_type']) ?></span>
              <?php if ($log['entity_label']): ?>
                <div style="font-weight:600;color:var(--navy-700)"><?= e($log['entity_label']) ?></div>
              <?php endif; ?>
            <?php else: ?>—<?php endif; ?>
          </td>
          <td style="font-size:12px;color:var(--muted)"><?= $log['details'] ? e($log['details']) : '—' ?></td>
          <td style="font-size:11px;color:var(--muted);font-family:monospace"><?= e($log['ip_address'] ?? '—') ?></td>
        </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>

  <!-- Pagination -->
  <?php if ($pages > 1): ?>
  <div style="display:flex;justify-content:center;align-items:center;gap:6px;padding:16px;border-top:1px solid var(--border)">
    <?php
    $qBase = http_build_query(array_filter(['action'=>$filterAction,'user'=>$filterUser,'entity'=>$filterEntity,'date'=>$filterDate,'date_end'=>$filterDateEnd]));
    $qBase = $qBase ? '&'.$qBase : '';
    ?>
    <?php if ($page_num > 1): ?>
      <a href="?p=1<?= $qBase ?>" class="btn-icon bi-secondary bi-sm" style="width:32px">«</a>
      <a href="?p=<?= $page_num-1 ?><?= $qBase ?>" class="btn-icon bi-secondary bi-sm" style="width:32px">‹</a>
    <?php endif; ?>
    <?php for ($i = max(1,$page_num-3); $i <= min($pages,$page_num+3); $i++): ?>
      <a href="?p=<?= $i ?><?= $qBase ?>" class="btn-icon <?= $i===$page_num?'bi-gold':'bi-secondary' ?> bi-sm" style="width:32px"><?= $i ?></a>
    <?php endfor; ?>
    <?php if ($page_num < $pages): ?>
      <a href="?p=<?= $page_num+1 ?><?= $qBase ?>" class="btn-icon bi-secondary bi-sm" style="width:32px">›</a>
      <a href="?p=<?= $pages ?><?= $qBase ?>" class="btn-icon bi-secondary bi-sm" style="width:32px">»</a>
    <?php endif; ?>
    <span style="font-size:12px;color:var(--muted);margin-left:8px"><?= number_format($total) ?> total</span>
  </div>
  <?php endif; ?>
  <?php endif; ?>
</div>

<?php include __DIR__ . '/../includes/footer.php'; ?>
