<?php
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/helpers.php';
$user = require_login();
$pdo  = db();
$type = $_GET['type'] ?? 'csv';
$date = $_GET['date'] ?? date('Y-m-d');

$rows = hierarchy_summary($pdo, $date, $user);
$tot  = sum_totals($rows);

if ($type === 'csv') {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="UPF_MDD_Report_'.$date.'.csv"');
    $out = fopen('php://output','w');
    fputcsv($out,[APP_ORG]);
    fputcsv($out,[APP_NAME]);
    fputcsv($out,['Attendance Report — '.date('j F Y',strtotime($date))]);
    fputcsv($out,['Generated by: '.$user['full_name'].' on '.date('Y-m-d H:i')]);
    fputcsv($out,['Scope: '.user_scope_label($user)]);
    fputcsv($out,[]);
    fputcsv($out,['Unit','Total','Present','AWOL','Leave','Sick','Suspended','Disciplinary','On Duty','On Course','Unrecorded']);
    foreach ($rows as $r) {
        fputcsv($out,[$r['unit_name'],$r['total'],$r['present'],$r['awol'],$r['on_leave'],$r['sick'],$r['suspended'],$r['disciplinary'],$r['on_duty'],$r['on_course'],$r['unrecorded']]);
    }
    fputcsv($out,['TOTAL',$tot['total'],$tot['present'],$tot['awol'],$tot['on_leave'],$tot['sick'],$tot['suspended'],$tot['disciplinary'],$tot['on_duty'],$tot['on_course'],$tot['unrecorded']]);
    fclose($out); exit;
}

// Print/PDF
$logoData = base64_encode(file_get_contents(BASE_PATH.'/public/assets/logo.jpg'));
$reportScope = user_scope_label($user);
?><!doctype html>
<html><head><meta charset="utf-8"><title>UPF MDD Report — <?= e($date) ?></title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:Arial,sans-serif;font-size:11px;color:#111;background:#fff;padding:18px 24px}

/* ── Official UPF Header ── */
.upf-header{border-bottom:2.5px solid #111;padding-bottom:10px;margin-bottom:0}
.upf-main-title{text-align:center;font-size:14px;font-weight:700;letter-spacing:.5px;text-transform:uppercase;margin-bottom:8px}
.upf-identity{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:10px}
.upf-contact{font-size:9.5px;line-height:1.75}
.upf-logo-wrap{text-align:center}
.upf-logo-wrap img{width:72px;height:72px;object-fit:contain}
.upf-address{text-align:right;font-size:9.5px;line-height:1.75}
.upf-report-label{text-align:center;margin-top:10px;padding:6px 0;border-top:1px solid #111;border-bottom:2px solid #111}
.upf-report-label .rpt-title{font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.3px}
.upf-report-label .rpt-meta{font-size:10px;margin-top:2px}

/* ── Table ── */
table{width:100%;border-collapse:collapse;margin-top:14px;font-size:10px}
th{background:#1a2236;color:#fff;padding:6px 8px;text-align:left;font-size:9.5px;text-transform:uppercase;letter-spacing:.4px}
td{border:1px solid #c8cfd8;padding:5px 8px;text-align:left}
th{border:1px solid #1a2236}
tr:nth-child(even) td{background:#f5f7fa}
tr.total-row td{background:#e8ecf2;font-weight:700;border-top:2px solid #1a2236}

/* ── Footer / print controls ── */
.report-meta{font-size:9.5px;color:#555;margin:8px 0 14px;line-height:1.6}
.no-print-bar{margin-top:18px;display:flex;gap:10px;align-items:center}
.btn-print{padding:8px 18px;background:#1a2236;color:#fff;border:0;border-radius:5px;font-size:11px;cursor:pointer;font-weight:600}
.page-footer{margin-top:24px;border-top:1px solid #ccc;padding-top:6px;text-align:center;font-size:8.5px;color:#888}

@media print{
  body{padding:10px 14px}
  .no-print{display:none!important}
  body{-webkit-print-color-adjust:exact;print-color-adjust:exact}
}
</style></head>
<body>

<!-- ═══ Official UPF Header ═══ -->
<div class="upf-header">
  <div class="upf-main-title">UGANDA POLICE FORCE-(UPF)</div>
  <div class="upf-identity">
    <div class="upf-contact">
      Telegram: "GENPOL"<br>
      Telephone: 0414-233814/0414-250613<br>
      Fax: (0414)-255630<br>
      E-mail: upf@upf.go.ug<br>
      Website: www.upf.go.ug
    </div>
    <div class="upf-logo-wrap">
      <img src="data:image/jpeg;base64,<?= $logoData ?>" alt="UPF Crest">
    </div>
    <div class="upf-address">
      Plot 1-3/5 Naguru Area<br>
      Police Headquarters<br>
      P.O. Box 7055 Kampala, Uganda<br>
      www.upf.go.ug
    </div>
  </div>
  <div class="upf-report-label">
    <div class="rpt-title">MDD Attendance Report<?= $reportScope && $reportScope !== 'HQ' ? ' — '.e($reportScope) : '' ?></div>
    <div class="rpt-meta">Generated on: <?= date('j/F/Y', strtotime($date)) ?> &nbsp;|&nbsp; Date of Returns: <?= date('j F Y', strtotime($date)) ?></div>
  </div>
</div>

<div class="report-meta">
  Generated by: <strong><?= e($user['full_name']) ?></strong> (<?= e(role_label($user['role'])) ?>)
  &nbsp;·&nbsp; Printed: <?= date('j F Y, H:i') ?> hrs
  &nbsp;·&nbsp; Scope: <?= e($reportScope) ?>
</div>

<table>
  <thead><tr>
    <th>#</th><th>Unit</th><th>Total</th><th>Present</th><th>AWOL</th>
    <th>Leave</th><th>Sick</th><th>Suspended</th><th>Disciplinary</th>
    <th>On Duty</th><th>On Course</th><th>Unrecorded</th>
  </tr></thead>
  <tbody>
    <?php foreach ($rows as $i => $r): ?>
    <tr>
      <td><?= $i+1 ?></td>
      <td><?= e($r['unit_name']) ?></td><td><?= $r['total'] ?></td><td><?= $r['present'] ?></td>
      <td><?= $r['awol'] ?></td><td><?= $r['on_leave'] ?></td><td><?= $r['sick'] ?></td>
      <td><?= $r['suspended'] ?></td><td><?= $r['disciplinary'] ?></td>
      <td><?= $r['on_duty'] ?></td><td><?= $r['on_course'] ?></td><td><?= $r['unrecorded'] ?></td>
    </tr>
    <?php endforeach; ?>
    <tr class="total-row">
      <td colspan="2">TOTAL</td><td><?= $tot['total'] ?></td><td><?= $tot['present'] ?></td>
      <td><?= $tot['awol'] ?></td><td><?= $tot['on_leave'] ?></td><td><?= $tot['sick'] ?></td>
      <td><?= $tot['suspended'] ?></td><td><?= $tot['disciplinary'] ?></td>
      <td><?= $tot['on_duty'] ?></td><td><?= $tot['on_course'] ?></td><td><?= $tot['unrecorded'] ?></td>
    </tr>
  </tbody>
</table>

<div class="page-footer">
  Uganda Police Force — MDD Management System &nbsp;·&nbsp; <?= date('Y') ?> &nbsp;·&nbsp; PROTECT &amp; SERVE
</div>

<div class="no-print no-print-bar">
  <button class="btn-print" onclick="window.print()">🖨 Print / Save as PDF</button>
</div>
</body></html>
