<?php
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/helpers.php';
$user = require_login();
$pdo  = db();
$type = $_GET['type'] ?? 'csv';
$date = $_GET['date'] ?? date('Y-m-d');

$rows = hierarchy_summary($pdo, $date, $user);
$tot  = sum_totals($rows);

if ($type === 'csv') {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="UPF_MDD_Report_'.$date.'.csv"');
    $out = fopen('php://output','w');
    fputcsv($out,[APP_ORG]);
    fputcsv($out,[APP_NAME]);
    fputcsv($out,['Attendance Report — '.date('j F Y',strtotime($date))]);
    fputcsv($out,['Generated by: '.$user['full_name'].' on '.date('Y-m-d H:i')]);
    fputcsv($out,['Scope: '.user_scope_label($user)]);
    fputcsv($out,[]);
    fputcsv($out,['Unit','Total','Present','AWOL','Leave','Sick','Suspended','Disciplinary','On Duty','On Course','Unrecorded']);
    foreach ($rows as $r) {
        fputcsv($out,[$r['unit_name'],$r['total'],$r['present'],$r['awol'],$r['on_leave'],$r['sick'],$r['suspended'],$r['disciplinary'],$r['on_duty'],$r['on_course'],$r['unrecorded']]);
    }
    fputcsv($out,['TOTAL',$tot['total'],$tot['present'],$tot['awol'],$tot['on_leave'],$tot['sick'],$tot['suspended'],$tot['disciplinary'],$tot['on_duty'],$tot['on_course'],$tot['unrecorded']]);
    fclose($out); exit;
}

// Print/PDF
$logoData = base64_encode(file_get_contents(BASE_PATH.'/public/assets/logo.jpg'));
?><!doctype html>
<html><head><meta charset="utf-8"><title>UPF Report — <?= e($date) ?></title>
<style>
body{font-family:Arial,sans-serif;color:#1a2236;margin:30px}
.head{display:flex;align-items:center;gap:16px;border-bottom:3px solid #d4a017;padding-bottom:12px;margin-bottom:18px}
.head img{width:70px;height:70px;border-radius:50%;border:2px solid #d4a017}
.head .org{font-weight:700;letter-spacing:1px;color:#0d1629}
.head .sys{font-size:13px;color:#475569}
.head .motto{font-size:11px;font-style:italic;letter-spacing:2px;color:#64748b}
table{width:100%;border-collapse:collapse;margin-top:14px}
th,td{border:1px solid #cbd5e1;padding:6px 8px;font-size:11px;text-align:left}
th{background:#0d1629;color:#fff}
tr.total-row{background:#f1f5f9;font-weight:700}
.meta{color:#64748b;font-size:12px;margin-bottom:10px}
@media print{.no-print{display:none}}
</style></head>
<body>
<div class="head">
  <img src="data:image/jpeg;base64,<?= $logoData ?>" alt="UPF">
  <div><div class="org"><?= e(APP_ORG) ?></div><div class="sys"><?= e(APP_NAME) ?></div><div class="motto"><?= e(APP_MOTTO) ?></div></div>
</div>
<h2 style="margin:0">Attendance Report — <?= e(date('j F Y',strtotime($date))) ?></h2>
<div class="meta">Generated by <?= e($user['full_name']) ?> (<?= e(role_label($user['role'])) ?>) · <?= date('j F Y H:i') ?> · Scope: <?= e(user_scope_label($user)) ?></div>
<table>
  <thead><tr><th>Unit</th><th>Total</th><th>Present</th><th>AWOL</th><th>Leave</th><th>Sick</th><th>Suspended</th><th>Disciplinary</th><th>On Duty</th><th>On Course</th><th>Unrecorded</th></tr></thead>
  <tbody>
    <?php foreach ($rows as $r): ?>
    <tr><td><?= e($r['unit_name']) ?></td><td><?= $r['total'] ?></td><td><?= $r['present'] ?></td>
      <td><?= $r['awol'] ?></td><td><?= $r['on_leave'] ?></td><td><?= $r['sick'] ?></td>
      <td><?= $r['suspended'] ?></td><td><?= $r['disciplinary'] ?></td>
      <td><?= $r['on_duty'] ?></td><td><?= $r['on_course'] ?></td><td><?= $r['unrecorded'] ?></td></tr>
    <?php endforeach; ?>
    <tr class="total-row"><td>TOTAL</td><td><?= $tot['total'] ?></td><td><?= $tot['present'] ?></td>
      <td><?= $tot['awol'] ?></td><td><?= $tot['on_leave'] ?></td><td><?= $tot['sick'] ?></td>
      <td><?= $tot['suspended'] ?></td><td><?= $tot['disciplinary'] ?></td>
      <td><?= $tot['on_duty'] ?></td><td><?= $tot['on_course'] ?></td><td><?= $tot['unrecorded'] ?></td></tr>
  </tbody>
</table>
<div class="no-print" style="margin-top:18px">
  <button onclick="window.print()" style="padding:8px 16px;background:#0d1629;color:#fff;border:0;border-radius:6px;cursor:pointer">Print / Save as PDF</button>
</div>
</body></html>
