<?php
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/helpers.php';
$user = require_min_rank('station_commander');
$page = 'history';
$page_title = 'Report History';
$pdo = db();
[$scopeW,$scopeP] = scope_where_for($user,'r');

if ($_SERVER['REQUEST_METHOD']==='POST') {
    $rid=(int)$_POST['id']; $notes=$_POST['notes']??''; $action=$_POST['action']??'';
    $rep=$pdo->query("SELECT * FROM reports WHERE id=$rid")->fetch();
    if ($rep && in_array($rep['status'],['pending_superadmin','pending_commander'],true)) {
        if ($action==='approve') {
            $pdo->prepare("UPDATE reports SET status='approved',reviewed_by=?,reviewed_at=?,review_notes=? WHERE id=?")->execute([$user['id'],date('c'),$notes,$rid]);
            flash('msg','Report approved.');
        } elseif ($action==='reject') {
            $pdo->prepare("UPDATE reports SET status='rejected',reviewed_by=?,reviewed_at=?,review_notes=? WHERE id=?")->execute([$user['id'],date('c'),$notes,$rid]);
            flash('msg','Report rejected.');
        }
    }
    header('Location:/history.php'.(!empty($_POST['ret'])?'?id='.(int)$_POST['ret']:'')); exit;
}

$statusFilter = $_GET['status'] ?? '';
$addWhere = ''; $addP = [];
if ($statusFilter && in_array($statusFilter,['pending_superadmin','pending_commander','approved','rejected'],true)) {
    $addWhere = ' AND r.status=?'; $addP[]=$statusFilter;
}

$reports=$pdo->prepare("
    SELECT r.*, u.full_name AS generator, rv.full_name AS reviewer
    FROM reports r
    LEFT JOIN users u ON u.id=r.generated_by
    LEFT JOIN users rv ON rv.id=r.reviewed_by
    WHERE $scopeW $addWhere
    ORDER BY CASE r.status WHEN 'pending_superadmin' THEN 1 WHEN 'pending_commander' THEN 1 ELSE 2 END, r.generated_at DESC
    LIMIT 200
");
$reports->execute(array_merge($scopeP,$addP));
$reports=$reports->fetchAll();

$detail=null;
if (!empty($_GET['id'])) {
    $detail=$pdo->query("SELECT r.*,u.full_name AS generator,rv.full_name AS reviewer FROM reports r LEFT JOIN users u ON u.id=r.generated_by LEFT JOIN users rv ON rv.id=r.reviewed_by WHERE r.id=".(int)$_GET['id'])->fetch();
    if ($detail) $detail['summary']=json_decode($detail['summary_json'],true)??[];
}

function rep_pill(string $s): string {
    $map=['pending_superadmin'=>['Pending HQ','badge-sick'],'pending_commander'=>['Pending Commander','badge-sick'],'approved'=>['Approved','badge-present'],'rejected'=>['Rejected','badge-awol']];
    [$l,$c]=$map[$s]??[$s,'badge-admin'];
    return '<span class="badge '.$c.'">'.htmlspecialchars($l).'</span>';
}

include __DIR__ . '/../includes/header.php';
?>
<div class="page-header">
  <div><h1>Report History</h1><div class="desc">Submitted reports with approval status</div></div>
  <form method="get" class="form-row" style="margin:0">
    <div class="form-group"><label>Filter Status</label>
      <select name="status" onchange="this.form.submit()">
        <option value="">All</option>
        <?php foreach(['pending_superadmin'=>'Pending HQ','pending_commander'=>'Pending Commander','approved'=>'Approved','rejected'=>'Rejected'] as $k=>$v): ?>
          <option value="<?= $k ?>" <?= $statusFilter===$k?'selected':'' ?>><?= e($v) ?></option>
        <?php endforeach; ?>
      </select>
    </div>
  </form>
</div>
<?php if ($m=flash('msg')): ?><div class="alert alert-success"><?= e($m) ?></div><?php endif; ?>

<div class="card">
  <div class="table-wrap">
    <table>
      <thead><tr><th>Date</th><th>Level</th><th>Status</th><th>Generated By</th><th>Reviewed By</th><th></th></tr></thead>
      <tbody>
        <?php foreach ($reports as $r): ?>
        <tr>
          <td><?= e(date('j M Y',strtotime($r['date']))) ?></td>
          <td><?= e(ucfirst($r['scope_level'])) ?></td>
          <td><?= rep_pill($r['status']) ?></td>
          <td><?= e($r['generator']??'—') ?><br><span class="muted"><?= e(date('M j H:i',strtotime($r['generated_at']))) ?></span></td>
          <td><?= $r['reviewer'] ? e($r['reviewer']).'<br><span class="muted">'.e(date('M j H:i',strtotime($r['reviewed_at']))).'</span>' : '<span class="muted">—</span>' ?></td>
          <td><a class="btn btn-sm btn-secondary" href="/history.php?id=<?= $r['id'] ?>">View</a></td>
        </tr>
        <?php endforeach; ?>
        <?php if (!$reports): ?><tr><td colspan="6" style="text-align:center;color:var(--muted);padding:24px">No reports found.</td></tr><?php endif; ?>
      </tbody>
    </table>
  </div>
</div>

<?php if ($detail): ?>
<div class="card">
  <div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:10px">
    <h3 style="margin:0">Report — <?= e(date('j F Y',strtotime($detail['date']))) ?> · <?= rep_pill($detail['status']) ?></h3>
    <a class="btn btn-secondary btn-sm" href="/history.php">← Back</a>
  </div>
  <div class="muted" style="margin:6px 0 14px">Generated by <?= e($detail['generator']??'—') ?> · <?= e(date('Y-m-d H:i',strtotime($detail['generated_at']))) ?>
    <?= $detail['reviewer'] ? ' · Reviewed by '.e($detail['reviewer']) : '' ?>
    <?= $detail['review_notes'] ? '<br>Notes: '.e($detail['review_notes']) : '' ?>
  </div>
  <?php if (in_array($detail['status'],['pending_superadmin','pending_commander'],true) && role_rank($user['role']) >= role_rank('regional_commander')): ?>
  <form method="post" style="display:flex;gap:8px;flex-wrap:wrap;align-items:center;background:var(--navy-50);padding:12px;border-radius:8px;margin-bottom:14px">
    <input type="hidden" name="id" value="<?= $detail['id'] ?>">
    <input type="hidden" name="ret" value="<?= $detail['id'] ?>">
    <input type="text" name="notes" placeholder="Review notes (optional)" style="flex:1;min-width:200px">
    <button class="btn" name="action" value="approve">Approve</button>
    <button class="btn btn-danger" name="action" value="reject">Reject</button>
  </form>
  <?php endif; ?>
  <div class="table-wrap"><table>
    <thead><tr><th>Unit</th><th>Total</th><th>Present</th><th>AWOL</th><th>Leave</th><th>Sick</th><th>Suspended</th><th>Disciplinary</th><th>On Duty</th><th>On Course</th></tr></thead>
    <tbody>
      <?php foreach ($detail['summary'] as $s): ?>
      <tr><td><?= e($s['unit_name']??$s['branch_name']??'—') ?></td><td><?= $s['total'] ?></td><td><?= $s['present'] ?></td>
        <td><?= $s['awol'] ?></td><td><?= $s['on_leave'] ?></td><td><?= $s['sick'] ?></td>
        <td><?= $s['suspended']??0 ?></td><td><?= $s['disciplinary']??0 ?></td>
        <td><?= $s['on_duty']??0 ?></td><td><?= $s['on_course']??0 ?></td></tr>
      <?php endforeach; ?>
    </tbody>
  </table></div>
</div>
<?php endif; ?>
<?php include __DIR__ . '/../includes/footer.php'; ?>
