<?php
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/helpers.php';
$user = require_min_rank('station_commander');
$page = 'history';
$page_title = 'Report History';
$pdo = db();
[$scopeW,$scopeP] = scope_where_for($user,'r');

if ($_SERVER['REQUEST_METHOD']==='POST') {
    $rid=(int)$_POST['id']; $notes=$_POST['notes']??''; $action=$_POST['action']??'';
    $rep=$pdo->query("SELECT * FROM reports WHERE id=$rid")->fetch();
    if ($rep && in_array($rep['status'],['pending_superadmin','pending_commander'],true)) {
        if ($action==='approve') {
            $pdo->prepare("UPDATE reports SET status='approved',reviewed_by=?,reviewed_at=?,review_notes=? WHERE id=?")->execute([$user['id'],date('c'),$notes,$rid]);
            flash('msg','Report approved.');
        } elseif ($action==='reject') {
            $pdo->prepare("UPDATE reports SET status='rejected',reviewed_by=?,reviewed_at=?,review_notes=? WHERE id=?")->execute([$user['id'],date('c'),$notes,$rid]);
            flash('msg','Report rejected.');
        }
    }
    header('Location:/history.php'.(!empty($_POST['ret'])?'?id='.(int)$_POST['ret']:'')); exit;
}

$statusFilter = $_GET['status'] ?? '';
$addWhere=''; $addP=[];
if ($statusFilter && in_array($statusFilter,['pending_superadmin','pending_commander','approved','rejected'],true)) {
    $addWhere=' AND r.status=?'; $addP[]=$statusFilter;
}
$reports=$pdo->prepare("SELECT r.*, u.full_name AS generator, rv.full_name AS reviewer FROM reports r LEFT JOIN users u ON u.id=r.generated_by LEFT JOIN users rv ON rv.id=r.reviewed_by WHERE $scopeW $addWhere ORDER BY CASE r.status WHEN 'pending_superadmin' THEN 1 WHEN 'pending_commander' THEN 1 ELSE 2 END, r.generated_at DESC LIMIT 200");
$reports->execute(array_merge($scopeP,$addP));
$reports=$reports->fetchAll();

$detail=null;
if (!empty($_GET['id'])) {
    $detail=$pdo->query("SELECT r.*,u.full_name AS generator,rv.full_name AS reviewer FROM reports r LEFT JOIN users u ON u.id=r.generated_by LEFT JOIN users rv ON rv.id=r.reviewed_by WHERE r.id=".(int)$_GET['id'])->fetch();
    if ($detail) $detail['summary']=json_decode($detail['summary_json'],true)??[];
}

function rep_pill(string $s): string {
    $map=['pending_superadmin'=>['Pending HQ','badge-sick'],'pending_commander'=>['Pending Cmd','badge-sick'],'approved'=>['Approved','badge-present'],'rejected'=>['Rejected','badge-awol']];
    [$l,$c]=$map[$s]??[$s,'badge-admin'];
    return '<span class="badge '.$c.'">'.htmlspecialchars($l).'</span>';
}

include __DIR__ . '/../includes/header.php';
?>
<div class="page-header">
  <div><h1>Report History</h1><div class="desc">Submitted reports with approval workflow</div></div>
  <div class="action-bar">
    <!-- Filter picker -->
    <details class="form-panel">
      <summary><button type="button" class="btn-icon bi-secondary" title="Filter by status"><?= ICO_SEARCH ?></button></summary>
      <div class="form-body" style="padding:12px 16px">
        <form method="get" style="display:flex;gap:8px;align-items:flex-end">
          <div class="form-group"><label>Status</label>
            <select name="status">
              <option value="">All</option>
              <?php foreach(['pending_superadmin'=>'Pending HQ','pending_commander'=>'Pending Cmd','approved'=>'Approved','rejected'=>'Rejected'] as $k=>$v): ?>
                <option value="<?= $k ?>" <?= $statusFilter===$k?'selected':'' ?>><?= e($v) ?></option>
              <?php endforeach; ?>
            </select>
          </div>
          <button class="btn-icon bi-primary" type="submit" title="Apply"><?= ICO_SAVE ?></button>
        </form>
      </div>
    </details>
    <?php if ($detail): ?><a class="btn-icon bi-secondary" href="/history.php" title="Back to list"><?= ICO_CANCEL ?></a><?php endif; ?>
  </div>
</div>

<?php if ($m=flash('msg')): ?><div class="alert alert-success"><?= e($m) ?></div><?php endif; ?>

<div class="card">
  <div class="table-wrap">
    <table>
      <thead><tr><th>Date</th><th>Level</th><th>Status</th><th>Generated By</th><th>Reviewed By</th><th style="width:48px"></th></tr></thead>
      <tbody>
        <?php foreach ($reports as $r): ?>
        <tr>
          <td><?= e(date('j M Y',strtotime($r['date']))) ?></td>
          <td><?= e(ucfirst($r['scope_level'])) ?></td>
          <td><?= rep_pill($r['status']) ?></td>
          <td><?= e($r['generator']??'—') ?><br><span class="muted"><?= e(date('M j H:i',strtotime($r['generated_at']))) ?></span></td>
          <td><?= $r['reviewer'] ? e($r['reviewer']).'<br><span class="muted">'.e(date('M j H:i',strtotime($r['reviewed_at']))).'</span>' : '<span class="muted">—</span>' ?></td>
          <td><a class="btn-icon bi-secondary bi-sm" href="/history.php?id=<?= $r['id'] ?>" title="View report"><?= ICO_EYE ?></a></td>
        </tr>
        <?php endforeach; ?>
        <?php if (!$reports): ?><tr><td colspan="6" style="text-align:center;color:var(--muted);padding:24px">No reports found.</td></tr><?php endif; ?>
      </tbody>
    </table>
  </div>
</div>

<?php if ($detail): ?>
<div class="card">
  <div class="chr">
    <h3>Report — <?= e(date('j F Y',strtotime($detail['date']))) ?> · <?= rep_pill($detail['status']) ?></h3>
  </div>
  <div class="muted" style="margin:0 0 14px;font-size:12px">
    Generated by <?= e($detail['generator']??'—') ?> · <?= e(date('Y-m-d H:i',strtotime($detail['generated_at']))) ?>
    <?= $detail['reviewer'] ? ' · Reviewed by '.e($detail['reviewer']) : '' ?>
    <?= $detail['review_notes'] ? '<br>Notes: '.e($detail['review_notes']) : '' ?>
  </div>
  <?php if (in_array($detail['status'],['pending_superadmin','pending_commander'],true) && role_rank($user['role']) >= role_rank('regional_commander')): ?>
  <details class="form-panel" style="margin-bottom:14px" open>
    <summary><button type="button" class="btn-icon bi-secondary" title="Approve / Reject"><?= ICO_EYE ?></button></summary>
    <div class="form-body">
      <form method="post" style="display:flex;gap:8px;flex-wrap:wrap;align-items:flex-end">
        <input type="hidden" name="id" value="<?= $detail['id'] ?>"><input type="hidden" name="ret" value="<?= $detail['id'] ?>">
        <div class="form-group" style="flex:1"><label>Review Notes</label><input type="text" name="notes" placeholder="Optional notes"></div>
        <div class="action-bar">
          <button class="btn-icon bi-green bi-lg" name="action" value="approve" title="Approve report"><?= ICO_OK ?></button>
          <button class="btn-icon bi-danger bi-lg" name="action" value="reject" title="Reject report"><?= ICO_REJECT ?></button>
        </div>
      </form>
    </div>
  </details>
  <?php endif; ?>
  <div class="table-wrap">
    <table>
      <thead><tr><th>Unit</th><th>Total</th><th>Present</th><th>AWOL</th><th>Leave</th><th>Sick</th><th>Suspended</th><th>Disciplinary</th><th>On Duty</th><th>On Course</th></tr></thead>
      <tbody>
        <?php foreach ($detail['summary'] as $s): ?>
        <tr><td><?= e($s['unit_name']??$s['branch_name']??'—') ?></td><td><?= $s['total'] ?></td><td><?= $s['present'] ?></td>
          <td><?= $s['awol'] ?></td><td><?= $s['on_leave'] ?></td><td><?= $s['sick'] ?></td>
          <td><?= $s['suspended']??0 ?></td><td><?= $s['disciplinary']??0 ?></td>
          <td><?= $s['on_duty']??0 ?></td><td><?= $s['on_course']??0 ?></td></tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
</div>
<?php endif; ?>

<script>
document.querySelectorAll('details.form-panel').forEach(d=>{
  d.addEventListener('toggle',()=>{ if(d.open) document.querySelectorAll('details.form-panel').forEach(o=>{ if(o!==d) o.open=false; }); });
});
</script>
<?php include __DIR__ . '/../includes/footer.php'; ?>
