<?php
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/helpers.php';
$user = require_login();
$pdo  = db();
$format = $_GET['format'] ?? 'csv';
$date = $_GET['date'] ?? date('Y-m-d');

$rows = hierarchy_summary($pdo, $date, $user);
$tot  = sum_totals($rows);

$chartData = [
    ['present',      'Present',      '#22c55e'],
    ['on_duty',      'On Duty',      '#0891b2'],
    ['on_leave',     'On Leave',     '#3b82f6'],
    ['sick',         'Sick',         '#f59e0b'],
    ['on_course',    'On Course',    '#059669'],
    ['awol',         'AWOL',         '#ef4444'],
    ['suspended',    'Suspended',    '#7c3aed'],
    ['disciplinary', 'Disciplinary', '#dc2626'],
    ['deserted',     'Deserted',     '#be185d'],
    ['unrecorded',   'Unrecorded',   '#94a3b8'],
];
$chartTotal = 0;
foreach ($chartData as [$ck, $cl, $cc]) { $chartTotal += ($tot[$ck] ?? 0); }

if ($format === 'csv') {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="UPF_Status_Distribution_'.$date.'.csv"');
    $out = fopen('php://output','w');
    fputcsv($out, [APP_ORG]);
    fputcsv($out, [APP_NAME]);
    fputcsv($out, ['Status Distribution — '.date('j F Y',strtotime($date))]);
    fputcsv($out, ['Generated by: '.$user['full_name'].' on '.date('Y-m-d H:i')]);
    fputcsv($out, ['Scope: '.user_scope_label($user)]);
    fputcsv($out, []);
    fputcsv($out, ['Status','Count','Percentage']);
    foreach ($chartData as [$ck, $cl, $cc]) {
        $v = $tot[$ck] ?? 0;
        $pct = $chartTotal > 0 ? round($v / $chartTotal * 100) : 0;
        fputcsv($out, [$cl, $v, $pct.'%']);
    }
    fputcsv($out, ['TOTAL', $chartTotal, '100%']);
    fclose($out); exit;
}

$logoData = base64_encode(file_get_contents(BASE_PATH.'/public/assets/logo.jpg'));
$reportScope = user_scope_label($user);
?><!doctype html>
<html><head><meta charset="utf-8"><title>UPF Status Distribution — <?= e($date) ?></title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:Arial,sans-serif;font-size:11px;color:#111;background:#fff;padding:18px 24px}
.upf-header{border-bottom:2.5px solid #111;padding-bottom:10px;margin-bottom:0}
.upf-main-title{text-align:center;font-size:14px;font-weight:700;letter-spacing:.5px;text-transform:uppercase;margin-bottom:8px}
.upf-identity{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:10px}
.upf-contact{font-size:9.5px;line-height:1.75}
.upf-logo-wrap{text-align:center}
.upf-logo-wrap img{width:72px;height:72px;object-fit:contain}
.upf-address{text-align:right;font-size:9.5px;line-height:1.75}
.upf-report-label{text-align:center;margin-top:10px;padding:6px 0;border-top:1px solid #111;border-bottom:2px solid #111}
.upf-report-label .rpt-title{font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.3px}
.upf-report-label .rpt-meta{font-size:10px;margin-top:2px}
.chart-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:14px}
.chart-card{border:1px solid #c8cfd8;border-radius:6px;padding:12px}
.chart-card h4{font-size:11px;text-transform:uppercase;letter-spacing:.4px;margin-bottom:8px;color:#1a2236}
table{width:100%;border-collapse:collapse;font-size:10px}
th{background:#1a2236;color:#fff;padding:6px 8px;text-align:left;font-size:9.5px;text-transform:uppercase;letter-spacing:.4px}
td{border:1px solid #c8cfd8;padding:5px 8px}
th{border:1px solid #1a2236}
tr:nth-child(even) td{background:#f5f7fa}
.bar-track{height:12px;background:#eef1f5;border-radius:6px;overflow:hidden}
.bar-fill{height:100%;border-radius:6px}
.report-meta{font-size:9.5px;color:#555;margin:8px 0 14px;line-height:1.6}
.page-footer{margin-top:24px;border-top:1px solid #ccc;padding-top:6px;text-align:center;font-size:8.5px;color:#888}
.no-print-bar{margin-top:18px;display:flex;gap:10px;align-items:center}
.btn-print{padding:8px 18px;background:#1a2236;color:#fff;border:0;border-radius:5px;font-size:11px;cursor:pointer;font-weight:600}
@media print{
  body{padding:10px 14px}
  .no-print{display:none!important}
  body{-webkit-print-color-adjust:exact;print-color-adjust:exact}
}
</style></head>
<body>

<div class="upf-header">
  <div class="upf-main-title">UGANDA POLICE FORCE-(UPF)</div>
  <div class="upf-identity">
    <div class="upf-contact">
      Telegram: "GENPOL"<br>
      Telephone: 0414-233814/0414-250613<br>
      Fax: (0414)-255630<br>
      E-mail: upf@upf.go.ug<br>
      Website: www.upf.go.ug
    </div>
    <div class="upf-logo-wrap"><img src="data:image/jpeg;base64,<?= $logoData ?>" alt="UPF Crest"></div>
    <div class="upf-address">
      Plot 1-3/5 Naguru Area<br>
      Police Headquarters<br>
      P.O. Box 7055 Kampala, Uganda<br>
      www.upf.go.ug
    </div>
  </div>
  <div class="upf-report-label">
    <div class="rpt-title">Personnel Status Distribution<?= $reportScope && $reportScope !== 'HQ' ? ' — '.e($reportScope) : '' ?></div>
    <div class="rpt-meta">Generated on: <?= date('j/F/Y', strtotime($date)) ?> &nbsp;|&nbsp; Date of Returns: <?= date('j F Y', strtotime($date)) ?></div>
  </div>
</div>

<div class="report-meta">
  Generated by: <strong><?= e($user['full_name']) ?></strong> (<?= e(role_label($user['role'])) ?>)
  &nbsp;·&nbsp; Printed: <?= date('j F Y, H:i') ?> hrs
  &nbsp;·&nbsp; Scope: <?= e($reportScope) ?>
</div>

<div class="chart-grid">
  <div class="chart-card">
    <h4>Distribution by Status</h4>
    <table>
      <thead><tr><th>Status</th><th>Count</th><th>% Share</th></tr></thead>
      <tbody>
        <?php foreach ($chartData as [$ck, $cl, $cc]):
          $v = $tot[$ck] ?? 0;
          $pct = $chartTotal > 0 ? round($v / $chartTotal * 100) : 0;
          $w = $chartTotal > 0 ? max(2, round($v / $chartTotal * 100)) : 0; ?>
        <tr>
          <td><span style="display:inline-block;width:9px;height:9px;border-radius:50%;background:<?= $cc ?>;margin-right:6px"></span><?= $cl ?></td>
          <td><?= $v ?></td>
          <td><?= $pct ?>%</td>
        </tr>
        <?php endforeach; ?>
        <tr style="font-weight:700;background:#e8ecf2"><td>TOTAL</td><td><?= $chartTotal ?></td><td>100%</td></tr>
      </tbody>
    </table>
  </div>
  <div class="chart-card">
    <h4>Bars — Relative Share</h4>
    <table style="border:none">
      <?php foreach ($chartData as [$ck, $cl, $cc]):
        $v = $tot[$ck] ?? 0;
        $pct = $chartTotal > 0 ? round($v / $chartTotal * 100) : 0;
        $w = $chartTotal > 0 ? max(2, round($v / $chartTotal * 100)) : 0; ?>
      <tr style="border:none">
        <td style="border:none;white-space:nowrap;width:110px"><?= $cl ?></td>
        <td style="border:none;padding:4px 2px"><div class="bar-track"><div class="bar-fill" style="width:<?= $w ?>%;background:<?= $cc ?>"></div></div></td>
        <td style="border:none;width:80px;text-align:right"><?= $v ?> (<?= $pct ?>%)</td>
      </tr>
      <?php endforeach; ?>
    </table>
  </div>
</div>

<div class="page-footer">
  Uganda Police Force — MDD Management System &nbsp;·&nbsp; <?= date('Y') ?> &nbsp;·&nbsp; PROTECT &amp; SERVE
</div>

<div class="no-print no-print-bar">
  <button class="btn-print" onclick="window.print()">🖨 Print / Save as PDF</button>
</div>
</body></html>
